#!/bin/bash

dir=$(zenity  --file-selection --title="Choose a directory" --directory)
zenity --info --title='Selected Directory' --text='You have selcted \n'$dir --timeout=1
gnome-terminal --working-directory=$dir
